services:
  - type: web
    name: rg-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m main.telegram_server
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromService: false
        sync: false
      - key: COHERE_API_KEY
        fromService: false
        sync: false
    region: oregon
